### ISSUE TITLE
"File" proptype is invalid and causes SSR to fail

### ISSUE THREAD

**Issue by syropian** [alessiomaffeis/vue-picture-input#29]
You have a `File` prop validation here https://github.com/alessiomaffeis/vue-picture-input/blob/master/PictureInput.vue#L88

but `File` is not in the list of valid types to check (https://vuejs.org/v2/guide/components.html#Prop-Validation) and it's actually causing SSR to fail with `ReferenceError: File is not defined`

**Comment by alessiomaffeis** [comment]
Hi, I know that it is not in the list of supported types, but it was the only way to make it work, since using the constructor didn't work at the time I wrote that.  

Have you tried that? Can you make a PR?  
A workaround would be disabling validation for that prop and checking the type in a watcher method.

**Comment by alessiomaffeis** [comment]
Any update on this issue?

**Comment by syropian** [comment]
Unfortunately don't have time to file a PR 😢

**Comment by simonmaass** [comment]
I have the same issue? Any update on how to fix this?
