### ISSUE TITLE
File not recognized by Laravel

### ISSUE THREAD

**Issue by axtg** [alessiomaffeis/vue-picture-input#68]
Unfortunately I wasn't able to use this package as is to process uploads via VueJS into Laravel for storing.
From my testing it seemed like Laravel was not getting enough file details (e.g. $request->file('file') and $request->hasFile('file') were failing.

Changing in PictureInput.vue the two references from **this.image** to **this.file** did the trick.

Not sure if this has anything to do with my setup, if not, then feel free to consider this as a code modification suggestion.

**Comment by alessiomaffeis** [comment]
That's because by default the image is provided as a base64 encoded string.
Here is how you could handle it in your Laravel app: https://laracasts.com/discuss/channels/laravel/create-image-from-base64-string-laravel/replies/415234

Not sure what changes did you make, but if you add `ref="pictureInput"` attribute  to the picture-input component in your app, you can access the File object directly, if you need that:`this.$refs.pictureInput.file`

**Comment by axtg** [comment]
Hi Alessio,

Excellent, thank you for thinking along. So this is what I do for my Axios post now, which allows me to do some Laravel server side checking on the file before storing, etc.

``
onChange (image) 
      {
        console.log('New picture selected!')
        if (image) {

          // Initialize form data and append file
          let formData = new FormData();
          formData.append('avatar', this.$refs.pictureInput.file);

          // Make axios request
          axios.post('/avatar', formData).then(response => 
          {
            console.log('Updated!');
          });
        } 
      }
``

In Laravel this allows me to do this $request->hasFile('avatar') and $request->file('avatar')->isValid() and e.g. also use the built-in helper getClientOriginalExtension() for storing the image under its original extension.
